force-app/main/default/objects/PlatformEvent__e/PlatformEvent__e.object-meta.xml
<CustomObject>
    <description></description>
    <label>Platform Event</label>
    <pluralLabel>Platform Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/PlatformEvent__e/fields/RecordJSON__c.field-meta.xml
<CustomField>
    <fullName>RecordJSON__c</fullName>
    <defaultValue>&quot;{&apos;field1&apos;:&apos;value1&apos;, &apos;field2&apos;:&apos;value2&apos;, &apos;field3&apos;:&apos;value3&apos;}&quot;</defaultValue>
    <label>Record JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlatformEventMapping__mdt/PlatformEventMapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to control the mapping from Salesforce Fields towards the Platform Object fields. Works in combination with FieldSet on each involved Object.
Account
Contact
Address
Quote</description>
    <label>Platform Event Mapping</label>
    <pluralLabel>Platform Event Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PlatformEventMapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlatformEventMapping__mdt/fields/Salesforce_Platform_Event_JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Platform_Event_JSONAttribute__c</fullName>
    <label>Salesforce Platform Event JSONAttribute</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PlatformEventMapping__mdt/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <label>SObject API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>QuoteLineItem</fullName>
            </value>
            <value>
                <fullName>SalesAreaData</fullName>
            </value>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>TerritoryUsers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublishPlatformEvents.cls
public with sharing class PublishPlatformEvents {
    @AuraEnabled
    public static void PublishPlatformEvent(String recordId, String objName){
        List<PlatformEvent__e> publishEvents = new List<PlatformEvent__e>();
        Map<String, Object> fieldToJSONMap = new Map<String, Object>();
        List<PlatformEventMapping__mdt> mappingsList = PlatformEventMapping__mdt.getall().values();
        String query = 'Select Id, ';
            for(Integer i=0 ; i < mappingsList.size(); i++) {
                if(mappingsList[i].SObject_API_Name__c == objName) {
                    query += mappingsList[i].Salesforce_Field_API_Name__c + ', ';
                }
            }
        query = query.removeEnd(', ')+' from '+objName +' where Id =: recordId';

        for(Sobject obj : Database.query(query)) {
            PlatformEvent__e platformEvent = new PlatformEvent__e();
            for(PlatformEventMapping__mdt actualMapping : mappingsList) {
                if(actualMapping.SObject_API_Name__c == objName) {
                        fieldToJSONMap.put(actualMapping.Salesforce_Platform_Event_JSONAttribute__c,
                        obj.get(actualMapping.Salesforce_Field_API_Name__c));
                }
                else
                {
                    continue;
                }
            }
            platformEvent.RecordId__c = obj.Id;
            platformEvent.RecordJSON__c = JSON.serializePretty(fieldToJSONMap);
            publishEvents.add(platformEvent);
        }
        System.debug('Publish Events: '+publishEvents);
        if(!publishEvents.isEmpty()) {
            Eventbus.publish(publishEvents);
        }   
    }
}